function [out1,Ts] = F_matrix(Ts)
%F_matrix
%    [OUT1,Ts] = F_matrix(Ts)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    14-Mar-2023 00:08:10

t2 = Ts.*-3.446514460369791e+2;
t3 = Ts.*3.446514460369791e+2;
t4 = Ts.*2.935472890335429e+3;
t5 = exp(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = t5.*t6;
t9 = t5.*t7.*1.103358443104912e-1;
out1 = reshape([t8-t9,t5.*t7.*1.535018463100945e+1,0.0,t5.*t7.*-6.593888105391128e-2,t8+t9,0.0,t8.*1.942433830519965e+1+t5.*t7.*2.280595507197331-1.942433830519965e+1,t8.*-6.708934400414343e+1+t5.*t7.*2.907648199050695e+2+6.708934400414343e+1,1.0],[3,3]);
if nargout > 1
    Ts = Ts;
end
