function [out1,Ts] = G_matrix(Ts)
%G_matrix
%    [OUT1,Ts] = G_matrix(Ts)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    14-Mar-2023 00:08:10

t2 = Ts.*-3.446514460369791e+2;
t3 = Ts.*3.446514460369791e+2;
t4 = Ts.*2.935472890335429e+3;
t5 = exp(t2);
t6 = cos(t4);
t7 = sin(t4);
out1 = [t5.*t6.*-4.463385332301259e-4+t5.*t7.*6.391906607306209e-2+4.463385332301259e-4;t5.*t6.*-9.686215160662221e-1-t5.*t7.*1.13725051685491e-1+9.686215160662221e-1;0.0];
if nargout > 1
    Ts = Ts;
end
