function [out1,Ts] = R_matrix(Ts)
%R_matrix
%    [OUT1,Ts] = R_matrix(Ts)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    14-Mar-2023 00:08:15

t2 = 1.0./Ts;
out1 = reshape([t2.*2.568211702827088e-6,0.0,0.0,t2.*2.220660990245105e-1],[2,2]);
if nargout > 1
    Ts = Ts;
end
